<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>juicescript</RootNamespace>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <AssemblyVersion>1.0.0.3</AssemblyVersion>
    <Configurations>Debug;Release;Debug_Player;ReleasePlayer;ProfilePlayer</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleasePlayer|AnyCPU'">
    <Optimize>True</Optimize>
    <DefineConstants>$(DefineConstants);PLAYER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ProfilePlayer|AnyCPU'">
    <Optimize>True</Optimize>
    <DefineConstants>$(DefineConstants);PLAYER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug_Player|AnyCPU'">
    <DefineConstants>$(DefineConstants);PLAYER</DefineConstants>
  </PropertyGroup>

</Project>
