<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>juicescript.runtime</RootNamespace>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <Configurations>Debug;Release;Debug_Player;ReleasePlayer;ProfilePlayer</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleasePlayer|AnyCPU'">
    <Optimize>True</Optimize>
    <DefineConstants>$(DefineConstants);PLAYER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ProfilePlayer|AnyCPU'">
    <Optimize>True</Optimize>
    <DefineConstants>$(DefineConstants);PLAYER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);FORCOMPILER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);FORCOMPILER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug_Player|AnyCPU'">
    <DefineConstants>$(DefineConstants);PLAYER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\abc\abc.csproj" />
  </ItemGroup>

</Project>
