<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>juicescript.compiler</RootNamespace>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <AssemblyVersion>1.0.0.3</AssemblyVersion>
    <Configurations>Debug;Release;Debug_Player;ReleasePlayer;ProfilePlayer</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);FORCOMPILER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);FORCOMPILER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\runtime\*.cs">
      <Link>Rumtime\%(RecursivePath)%(Filename)%(Extension)</Link>
    </Compile>
	<Compile Include="..\runtime\gc\*.cs">
      <Link>Rumtime\gc\%(RecursivePath)%(Filename)%(Extension)</Link>
    </Compile>
	<Compile Include="..\runtime\buildin\*.cs">
      <Link>Rumtime\buildin\%(RecursivePath)%(Filename)%(Extension)</Link>
    </Compile>
	<Compile Include="..\runtime\buildin\Dota\*.cs">
      <Link>Rumtime\buildin\Dota\%(RecursivePath)%(Filename)%(Extension)</Link>
    </Compile>
	<Compile Include="..\runtime\buildin\Pooling\*.cs">
      <Link>Rumtime\buildin\Pooling\%(RecursivePath)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>

  
  
  <ItemGroup>
    <ProjectReference Include="..\abc\abc.csproj" />
  </ItemGroup>

</Project>
