<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Configurations>Debug;Release;Debug_Player;ReleasePlayer;ProfilePlayer</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);RUNTEST</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.0.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.0.4" />
    <PackageReference Include="Microsoft.Playwright.MSTest" Version="1.49.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\abc\abc.csproj" />
    <ProjectReference Include="..\asc\asc.csproj" />
    <ProjectReference Include="..\compiler\compiler.csproj" />
    <ProjectReference Include="..\runtime\runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CompileTest\uint\" />
    <Folder Include="CompileTest\int\" />
  </ItemGroup>

</Project>
